# Generated by Django 4.0.3 on 2023-08-11 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_location_picture_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='weather_url',
            field=models.URLField(null=True),
        ),
    ]
