# Generated by Django 4.0.3 on 2023-08-11 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_location_weather_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='weather_url',
        ),
    ]
